
name: Create Package

on:
  release:
 
jobs:
  Create:
    name: create package
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v2
       
       - name: Install EPM 
         run: apt-get install epm -y
       
       - name: Build Package
         run:  epm -n -f deb fetchconfig
       
       - name: Upload Release Asset
         id: upload-release-asset 
         uses: actions/upload-release-asset@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ github.event.release.upload_url }} 
           asset_path: ./linux-5.4-x86_64/fetchconfig-0.1.deb
           asset_name: fetchconfig-0.1.deb
           asset_content_type: application/deb
